### ISSUE TITLE
Looks like the LGTM badges are not updating

### ISSUE THREAD

**Issue by Borewit** [justlaputa/cue-parser#20]
I think the LGTM badges are still displaying old information.

You may need to tweak things on [lgtm.com](https://lgtm.com/projects/g/justlaputa/cue-parser/ci/).

Related #19

**Comment by justlaputa** [comment]
the config look ok. but the alerts seems to stopped on commit '860d5d7'
![Screen Shot 2019-08-20 at 17 33 38](https://user-images.githubusercontent.com/520836/63331509-cc215200-c370-11e9-89ac-fcc08af5c75a.png)

I want to wait for next master push, if the status does not update, I will check it again

**Comment by Borewit** [comment]
I made a number of small commits on the master, I am not so sure it will do the trick.

Maybe trigger a re-run. I cannot do it, because I am not a repo admin.

Strange.

**Comment by justlaputa** [comment]
got it. let me check later. 😄

**Comment by justlaputa** [comment]
seems it's working now. I haven't done anything.

**Comment by Borewit** [comment]
It looks like there service is a bit overloaded.
