### ISSUE TITLE
The result for all my cue files contain only one track due to this code.

### ISSUE THREAD

**Issue by hrandib** [justlaputa/cue-parser#22]
The sequence adds the second file to the array right after adding the first track at this point:
https://github.com/justlaputa/cue-parser/blob/0bad7ac49555a61382050a24352f2a11f5162320/lib/cue.ts#L117
Then, all remaining tracks add to this second file.
After all, the second file is removed at this point:
https://github.com/justlaputa/cue-parser/blob/0bad7ac49555a61382050a24352f2a11f5162320/lib/cue.ts#L64

**Comment by Borewit** [comment]
Can you please zip your cue file and drag it into the issue comment?

**Comment by hrandib** [comment]
[node-test.zip](https://github.com/justlaputa/cue-parser/files/4022237/node-test.zip)
Minimal reproducable code included

**Comment by Borewit** [comment]
I am sorry, I totally forgot about this issue @hrandib.

**Comment by Borewit** [comment]
Fixed in [v0.2.1](https://github.com/justlaputa/cue-parser/releases/tag/v0.2.1)
