### ISSUE TITLE
Cue sheet won't be opened if chardet detects ISO-8859-9 (instead of ISO-8859-1)

### ISSUE THREAD

**Issue by N0NamedGuy** [justlaputa/cue-parser#23]
Good night.

I have a cue sheet that chardet somehow determines it is encoded in ISO-8859-9. The cue file has no special characters whatsoever.

Because chardet detects ISO-8859-9 the check made at https://github.com/justlaputa/cue-parser/blob/0bad7ac49555a61382050a24352f2a11f5162320/lib/cue.ts#L48 does not set the encoding to binary, therefore passing it straight to fs.readFileSync (at https://github.com/justlaputa/cue-parser/blob/0bad7ac49555a61382050a24352f2a11f5162320/lib/cue.ts#L54), which in turn makes NodeJS crap itself, because it doesn't know how to handle this encoding.

Cheers,
David S.

**Comment by Borewit** [comment]
Fixed in [v0.2.1](https://github.com/justlaputa/cue-parser/releases/tag/v0.2.1)
