### ISSUE TITLE
parseTime with more than 2-digits-hours

### ISSUE THREAD

**Issue by Bludwarf** [justlaputa/cue-parser#4]
The **parseTime** function in **cue.js** is not able to parse time code when hours is greather than 99.

Though I know cuesheet file format is not intended to support it, would you please replace :

    var timePattern = /^(\d{2}):(\d{2}):(\d{2})$/,

by

    var timePattern = /^(\d{2,}):(\d{2}):(\d{2})$/,

This would allow any length for hour digits.

Thank you for your work :+1:

**Comment by justlaputa** [comment]
fixed by commit 8c3ac071
