### ISSUE TITLE
Unable to parse strange characters

### ISSUE THREAD

**Issue by volumio** [justlaputa/cue-parser#5]
When parsing .cue with non-english characters like è, a characters with a question mark is displayed. 
I attach a problematc .cue for reference:

`REM GENRE Pop
REM DATE 1992
REM DISCID EE0E0910
REM COMMENT "ExactAudioCopy v0.99pb4"
CATALOG 4509901590208
PERFORMER "Nomadi"
TITLE "Ma Noi No!"
FILE "Nomadi - Ma Noi No!.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Come potete giudicar"
    PERFORMER "Nomadi"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Noi non ci saremo"
    PERFORMER "Nomadi"
    INDEX 00 03:21:57
    INDEX 01 03:23:62
  TRACK 03 AUDIO
    TITLE "Dio � morto"
    PERFORMER "Nomadi"
    INDEX 00 06:16:00
    INDEX 01 06:17:57
  TRACK 04 AUDIO
    TITLE "Per fare un uomo"
    PERFORMER "Nomadi"
    INDEX 00 09:10:10
    INDEX 01 09:11:62
  TRACK 05 AUDIO
    TITLE "Ho difeso il mio amore"
    PERFORMER "Nomadi"
    INDEX 00 12:12:15
    INDEX 01 12:13:60
  TRACK 06 AUDIO
    TITLE "Canzone per un'amica"
    PERFORMER "Nomadi"
    INDEX 00 16:25:35
    INDEX 01 16:27:42
  TRACK 07 AUDIO
    TITLE "Io vagabondo"
    PERFORMER "Nomadi"
    INDEX 00 19:45:37
    INDEX 01 19:47:22
  TRACK 08 AUDIO
    TITLE "Crescerai"
    PERFORMER "Nomadi"
    INDEX 00 23:39:37
    INDEX 01 23:41:20
  TRACK 09 AUDIO
    TITLE "Un giorno insieme"
    PERFORMER "Nomadi"
    INDEX 00 27:15:55
    INDEX 01 27:17:35
  TRACK 10 AUDIO
    TITLE "Tutto a posto"
    PERFORMER "Nomadi"
    INDEX 00 30:40:22
    INDEX 01 30:42:22
      INDEX 01 30:42:22
  TRACK 11 AUDIO
    TITLE "Il vecchio e il bambino"
    PERFORMER "Nomadi"
    INDEX 00 34:22:17
    INDEX 01 34:23:72
  TRACK 12 AUDIO
    TITLE "Gordon"
    PERFORMER "Nomadi"
    INDEX 00 40:00:22
    INDEX 01 40:02:05
  TRACK 13 AUDIO
    TITLE "Il pilota di Hiroshima"
    PERFORMER "Nomadi"
    INDEX 00 44:28:62
    INDEX 01 44:30:40
  TRACK 14 AUDIO
    TITLE "Ma noi no!"
    PERFORMER "Nomadi"
    INDEX 00 47:44:17
    INDEX 01 47:45:57
  TRACK 15 AUDIO
    TITLE "I ragazzi dell'olivo"
    PERFORMER "Nomadi"
    INDEX 00 52:31:40
    INDEX 01 52:33:00
  TRACK 16 AUDIO
    TITLE "Gli aironi neri"
    PERFORMER "Nomadi"
    INDEX 00 55:14:22
    INDEX 01 55:15:65
`

I can't read such characters even from cmdline. Is there a solution for this?

**Comment by justlaputa** [comment]
hi, @volumio 

thanks for the report.

I'm guessing your file itself is not UTF8 encoded, can you confirm it? and also, if you could attach the original file, I can confirm this issue more easily. From the text you pasted, it's hard to find the original text.

**Comment by volumio** [comment]
Yes, the file is not UTF8 encoded. See here:
http://repo.volumio.org/Volumio2/Nomadi%20-%20Ma%20Noi%20No%21.cue

It would be great if the parser could automagically detect encoding and if !=utf-8 convert it

**Comment by justlaputa** [comment]
Hi, thanks for the confirm and the original file. It's clear. 
Auto detect and convert non-utf8 cue files could be a good feature, but I'm not planing to implement it any soon. For now, I recommend you convert your file to UTF8 manually and feed it to the parser.

**Comment by justlaputa** [comment]
I'm closing this PR for now.
